blank_issues_enabled: true
contact_links:
  - name: Shiny Tracker Wiki
    url: https://github.com/trevorrl/Shiny-Tracker/wiki
    about: Check out the wiki for information about the Shiny Tracker
  - name: Trevorrl's Discord Server
    url: https://discord.com/invite/JwdKW7K
    about: You can also contact me in my Discord if you have questions about the tracker